apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL'
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'alertmanager@your-domain.com'
      smtp_auth_username: 'your-email@gmail.com'
      smtp_auth_password: 'your-app-password'

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'slack-notifications'
      routes:
      - match:
          severity: critical
        receiver: 'pager-duty-critical'
        continue: true
      - match:
          severity: warning
        receiver: 'slack-notifications'

    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#alerts'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        send_resolved: true
        icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
        icon_emoji: ':warning:'
        actions:
        - type: button
          text: 'View in Grafana'
          url: '{{ template "slack.grafanaURL" . }}'
        - type: button
          text: 'View in Prometheus'
          url: '{{ template "slack.prometheusURL" . }}'

    - name: 'pager-duty-critical'
      pagerduty_configs:
      - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'
        description: '{{ template "pagerduty.description" . }}'
        severity: '{{ if eq .CommonAnnotations.severity "critical" }}critical{{ else }}warning{{ end }}'
        client: 'AlertManager'
        client_url: '{{ template "pagerduty.clientURL" . }}'

    - name: 'email-notifications'
      email_configs:
      - to: 'sre-team@your-domain.com'
        send_resolved: true
        headers:
          subject: '{{ template "email.subject" . }}'
        html: '{{ template "email.html" . }}'

    templates:
    - '/etc/alertmanager/template/*.tmpl'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
  namespace: monitoring
data:
  slack.title.tmpl: |
    {{ range .Alerts }}
      {{ .Annotations.summary }}
    {{ end }}

  slack.text.tmpl: |
    {{ range .Alerts }}
    *Alert:* {{ .Annotations.summary }}
    *Description:* {{ .Annotations.description }}
    *Severity:* {{ .Labels.severity }}
    *Service:* {{ .Labels.service }}
    *Namespace:* {{ .Labels.kubernetes_namespace }}
    *Pod:* {{ .Labels.kubernetes_pod_name }}
    *Started:* {{ .StartsAt | since }}
    {{ end }}

  slack.grafanaURL.tmpl: |
    https://grafana.your-domain.com/d/{{ .CommonLabels.job }}/{{ .CommonLabels.service }}

  slack.prometheusURL.tmpl: |
    https://prometheus.your-domain.com/graph?g0.expr={{ urlquery .CommonAnnotations.expr }}

  pagerduty.description.tmpl: |
    {{ range .Alerts }}
      {{ .Annotations.summary }}: {{ .Annotations.description }}
    {{ end }}

  pagerduty.clientURL.tmpl: |
    https://grafana.your-domain.com/d/{{ .CommonLabels.job }}/{{ .CommonLabels.service }}

  email.subject.tmpl: |
    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonAnnotations.summary }}

  email.html.tmpl: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>{{ template "email.subject" . }}</title>
    </head>
    <body>
      <h1>{{ template "email.subject" . }}</h1>
      <table>
        <tr>
          <th>Alert</th>
          <th>Description</th>
          <th>Severity</th>
          <th>Service</th>
          <th>Started</th>
        </tr>
        {{ range .Alerts }}
        <tr>
          <td>{{ .Annotations.summary }}</td>
          <td>{{ .Annotations.description }}</td>
          <td>{{ .Labels.severity }}</td>
          <td>{{ .Labels.service }}</td>
          <td>{{ .StartsAt | since }}</td>
        </tr>
        {{ end }}
      </table>
    </body>
    </html> 