apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth-service-pdb
  namespace: auth
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: auth-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-service-pdb
  namespace: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: image-storage-service-pdb
  namespace: image-storage
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: image-storage-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgresql-pdb
  namespace: infrastructure
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: postgresql
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: minio-pdb
  namespace: infrastructure
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: minio 