apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: auth
type: Opaque
data:
  jwt-secret: eW91ci1zZWNyZXQta2V5 # your-secret-key base64 encoded
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: api
type: Opaque
data:
  jwt-secret: eW91ci1zZWNyZXQta2V5 # your-secret-key base64 encoded
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: image-storage
type: Opaque
data:
  jwt-secret: eW91ci1zZWNyZXQta2V5 # your-secret-key base64 encoded
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
  namespace: auth
type: Opaque
data:
  db-password: YXV0aF9wYXNzd29yZA== # auth_password base64 encoded
---
apiVersion: v1
kind: Secret
metadata:
  name: api-db-secret
  namespace: api
type: Opaque
data:
  db-password: YXBpX3Bhc3N3b3Jk # api_password base64 encoded
---
apiVersion: v1
kind: Secret
metadata:
  name: image-db-secret
  namespace: image-storage
type: Opaque
data:
  db-password: aW1hZ2VfcGFzc3dvcmQ= # image_password base64 encoded
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: image-storage
type: Opaque
data:
  access-key: bWluaW9hZG1pbg== # minioadmin base64 encoded
  secret-key: bWluaW9hZG1pbg== # minioadmin base64 encoded 