apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    name: auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: api
  labels:
    name: api
---
apiVersion: v1
kind: Namespace
metadata:
  name: image-storage
  labels:
    name: image-storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
  labels:
    name: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx 