apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-storage-service
  namespace: image-storage
  labels:
    app: image-storage-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-storage-service
  template:
    metadata:
      labels:
        app: image-storage-service
    spec:
      containers:
      - name: image-storage-service
        image: abdulaziz5107/image-storage-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          value: "3003"
        - name: DB_HOST
          value: "postgresql.infrastructure.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "image_db"
        - name: DB_USER
          value: "image_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: image-db-secret
              key: db-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: jwt-secret
        - name: MINIO_ENDPOINT
          value: "minio.infrastructure.svc.cluster.local:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: secret-key
        - name: MINIO_BUCKET
          value: "images"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL 