apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth
  labels:
    app: auth-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
  selector:
    app: auth-service
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api
  labels:
    app: api-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3002
    protocol: TCP
  selector:
    app: api-service
---
apiVersion: v1
kind: Service
metadata:
  name: image-storage-service
  namespace: image-storage
  labels:
    app: image-storage-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3003
    protocol: TCP
  selector:
    app: image-storage-service 